### ISSUE TITLE
Ignore Atrribute

### ISSUE THREAD

**Issue by thnder** [proudmonkey/AutoWrapper#11]
Hi, your package is very useful. Can i suggest to add an IgnoreAction attribute for the actions ?

Thanks in advance
Stefano

**Comment by proudmonkey** [comment]
hi @thnder I'd glad that you find this useful. Would you mind giving it a star to show your support on this project? :)

For your request, can you give me a sample use-case of IgnoreAction so I can better understand the need for it? Thank you.

**Comment by thnder** [comment]
Yes of course and i'm sorry because i've not explained that.


   ```
[HttpGet] 
[WarpIgnore]
    public async Task<IActionResult> Get()
    {
        // this action will not be wrapped
       return Ok(myObject);
    }
```
So if i need some "normal" output i can do thaht without include this actions type or whitout using the startwith option.

**Comment by proudmonkey** [comment]
@thnder I got it. Thank you for the suggestion. I will keep you posted for updates. :)

**Comment by proudmonkey** [comment]
@thnder ,

Version 2.1.0 is now released and added the `[AutoWrapIgnore]` filter attribute for enpoints that don't need to be wrapped. For example:

```csharp
[HttpGet]
[AutoWrapIgnore]
public async Task<IActionResult> Get()
{
    var data = await _personManager.GetAllAsync();
    return Ok(data);
}
```

or

```csharp
[HttpGet]
[AutoWrapIgnore]
public async Task<IEnumerable<Person>> Get()
{
    return await _personManager.GetAllAsync();
}
```

Thank you for your valuable feedback! :)
