### ISSUE TITLE
Always  hide isError in response

### ISSUE THREAD

**Issue by utkugenel** [proudmonkey/AutoWrapper#111]
{
  "isError": true,
  "error": {
    "message": "Error msg."
  }
}

It would be nice to hide isError parameter.
If http status code is not 200 then it's an error.
I don't need to check isError parameter.

{
  "error": {
    "message": "Error msg."
  }
}

**Comment by proudmonkey** [comment]
The `isError` attribute should be hidden by default since `v4.3.1`. It was still added as part of the error response because others might still find it useful aside from looking into StatusCodes.

**Comment by arhen** [comment]
> The `isError` attribute should be hidden by default since `v4.3.1`. It was still added as part of the error response because others might still find it useful aside from looking into StatusCodes.

Yah, I found it very useless when using UnitTest. Expect Json structure with consistency among all status code is a standard good communicating data between server/clients.
