### ISSUE TITLE
Quick response to the client

### ISSUE THREAD

**Issue by scymen** [proudmonkey/AutoWrapper#12]
Thanks for your greate work.

Some times I like to response with a message "quickly", e.g.

`

            return Unauthorized("Access code error");

            return NotFound(new {  msg1="file abc.txt is gone", fileName2="efg"});

            return BadRequest("User name is null");

` 

How can I get the message on the client? 
I found the code in WrapperBase.cs Line 66 handle not success request. The `bodyAsText` has been igored. How about to keep the message and set to property(`Message`)  of `ApiResponse` in ApiResponse.cs? 
Thank you.

**Comment by proudmonkey** [comment]
Hi @scymen - Thank for your feedback. I'm glad that you have interest in using this library. :)

Down to  your question - the wrapper intent is to automatically capture not successful response and provide consistent message and format. I'll look into the scenario you describe and get back to you. For the time being,  If you want to return a custom message based on status, you can simply use the `ApiException` or `ApiResponse` object. You just have to make sure to pass along the status code.

**Comment by scymen** [comment]
Thank you. 

And yes you are right, I can use `ApiException` or `ApiResponse`. But I use a lot of "quick" responses in my code like `return OK(list);`.  `return Unauthorized("Access code error"); ` I'm too lazy to modify it. That's why I need an **AUTO** wrapper.  :joy:

**Comment by proudmonkey** [comment]
@scymen ,

Version `2.1.0` is now released and added support to override non-success message when using IActionResult return types.

Try it out and let me know. Closing this issue for now. :)
