### ISSUE TITLE
How to turn off default logging for autowrapper?

### ISSUE THREAD

**Issue by tarangpandya** [proudmonkey/AutoWrapper#13]
How do I turn off this Logging information ? 
Can we change log level to Trace for auto wrapper? 

https://github.com/proudmonkey/AutoWrapper/blob/0bd62aa91b1502689d07d6c012bcf05e9dab3c53/AutoWrapper/Base/WrapperBase.cs#L80

There are some instances where we would like to log information, but with autowrapper this puts logging for all single requests which becomes so noisy..

**Comment by proudmonkey** [comment]
@tarangpandya - great findings! I'll add an option to disable logging and set log levels.

Thanks for the suggestion! :)

**Comment by tarangpandya** [comment]
@proudmonkey - Thank You for quick response.

**Comment by proudmonkey** [comment]
@tarangpandya 

Version 2.1.0 is now released. You can now turn off Logging by setting `EnableResponseLogging` and `EnableExceptionLogging` options to `false` in `AutoWrapper` options. For example:

```csharp
 app.UseApiResponseAndExceptionWrapper(new AutoWrapperOptions { EnableResponseLogging = false, EnableExceptionLogging = false });
```

Thank you again for your valuable feedback! :)
