### ISSUE TITLE
Problem Details for HTTP APIs

### ISSUE THREAD

**Issue by sondreb** [proudmonkey/AutoWrapper#17]
In 2016, the IETF published this rfc: [Problem Details for HTTP APIs](https://tools.ietf.org/html/rfc7807)

I think it should be considered to have a way of quickly enable error response format in the AutoWrapper that aligns with this RFC.

Here is an article that explains it a bit, and links to a middleware that implements this already: https://lurumad.github.io/problem-details-an-standard-way-for-specifying-errors-in-http-api-responses-asp.net-core

**Comment by proudmonkey** [comment]
Interesting. Thank you for the suggestion, I'll review it and see what I can do.

**Comment by proudmonkey** [comment]
@sondreb just released a new version to support ProblemDetails. You can find it here: [AutoWrapper Now Supports Problem Details For Your ASP.NET Core APIs](http://vmsdurano.com/autowrapper-now-supports-problemdetails/http://vmsdurano.com/autowrapper-now-supports-problemdetails/)

Thank you so much for all your suggestions on improving this middleware! :)
