### ISSUE TITLE
JSON with HTML characters issue

### ISSUE THREAD

**Issue by ITninja04** [proudmonkey/AutoWrapper#19]
Out of the box any circular reference results in a 'nested' response:

![image](https://user-images.githubusercontent.com/15346572/71473818-543fba00-279e-11ea-97a7-e5da45849d55.png)

I've modified the code to support passing an option for Newtonsofts ReferenceLoopHandling, however this doesn't fix the problem. (I'll submit a PR, once we're able to resolve this).

All of my other controllers and methods work just fine, but none of them have a potential loop.

Here's my API Method that's problematic:
![image](https://user-images.githubusercontent.com/15346572/71473910-ae407f80-279e-11ea-82af-7ee270375a9f.png)

Here's one that works:
![image](https://user-images.githubusercontent.com/15346572/71473940-cd3f1180-279e-11ea-9a30-7055025af8f5.png)

The only real difference is the data source.

App is a Blazor App with MVC API Support
.NET Core 3.1

**Comment by ITninja04** [comment]
Okay so the whole circular reference part was a farce, I still am going to submit a PR since that was an issue to start.

The problem above is actually due to having HTML characters in my JSON.

This was the line that broke it:

        public static bool IsHtml(this string text)
        {
            Regex tagRegex = new Regex(@"<\s*([^ >]+)[^>]*>.*?<\s*/\s*\1\s*>");
            return tagRegex.IsMatch(text);
        }

For now I've just commented it out and returned false and it works.

**Comment by proudmonkey** [comment]
Thank you for the feedback! I haven't covered or tested JSON data with HTML on it. I'll check it out. Thank you!

**Comment by proudmonkey** [comment]
Fixed with PR : https://github.com/proudmonkey/AutoWrapper/pull/20
