### ISSUE TITLE
Showing CreatedAtAction IActionResult as ErrorResponse

### ISSUE THREAD

**Issue by mohitmunjal2801** [proudmonkey/AutoWrapper#23]
Used ActionResult Status 

**CreatedAtAction(nameof(GetById), new { id = result.Id }, result);**

Response From AutoWrapper 

**{
    "statusCode": 201,
    "isError": true,
    "responseException": {
        "exceptionMessage": "{\"id\":24,\"countryCode\":\"BHUtyhfsdg\",\"countryName\":\"Bhutan\",\"countryDescription\":\"Bhutan\",\"cultureName\":2}"
    }
}**

**Comment by proudmonkey** [comment]
Hi @mohitmunjal2801,

Good catch! I'll verify this behavior and fix when needed. I'll keep you posted. Thanks for your feedback!

**Comment by proudmonkey** [comment]
v3 has been released. You can see the updates here: https://www.nuget.org/packages/AutoWrapper.Core

Thank you!
