### ISSUE TITLE
BypassHTMLValidationEnsure amendment

### ISSUE THREAD

**Issue by shiroyama-kimi** [proudmonkey/AutoWrapper#24]
1. BypassHTMLValidation is not available in current release version on nuget
2. Add BypassHTMLValidationEnsure to ApiOnly only condition to ensure HTML within the payload for ApiOnly is also permitted if BypassHTMLValidation is set to true.
-----------------------------------------------------------------
`if (!context.Request.Path.StartsWithSegments(new PathString(_options.WrapWhenApiPathStartsWith))
                                && bodyAsText.IsHtml() && context.Response.StatusCode == Status200OK)`

`if (!context.Request.Path.StartsWithSegments(new PathString(_options.WrapWhenApiPathStartsWith))
                                && (!_options.BypassHTMLValidation && bodyAsText.IsHtml()) && context.Response.StatusCode == Status200OK)`

**Comment by proudmonkey** [comment]
@shiroyama-kimi Thanks for the feedback and my apology for the late response. I didn't get the chance to validate this yet because I've been busy the past few weeks. I'll work on this over the weekend or as soon as I can and rollout a new version to reflect this feature.

Thanks,
Vince

**Comment by proudmonkey** [comment]
v3 has been released. You can see the updates here: https://www.nuget.org/packages/AutoWrapper.Core

Note that ApiOnly already supports HTML within the payload. Thanks!
