### ISSUE TITLE
the problem of exceptionMessage To JSON

### ISSUE THREAD

**Issue by larssonsun** [proudmonkey/AutoWrapper#26]
when i use autowrapper , i will get a json result just like this:

{
"statusCode": 422,
"isError": true,
"responseException": {
"exceptionMessage": "{"Username":["username is needed."]}"
}
}

if not use autowrapper, it is :

{
"username": [
"username is needed."
]
}

and this：

{
    "statusCode": 400,
    "isError": true,
    "responseException": {
        "exceptionMessage": "{\"type\":\"https://tools.ietf.org/html/rfc7231#section-6.5.1\",\"title\":\"Bad Request\",\"status\":400,\"traceId\":\"|12b5128e-441a91a7c1e0b449.\"}"
    }
}

if not use autowrapper （ProblemDetail entity）:

{
    "type": "https://tools.ietf.org/html/rfc7231#section-6.5.1",
    "title": "Bad Request",
    "status": 400,
    "traceId": "|2fc8416d-4f4fdb099ade0681."
}

how can i fixed the value of "exceptionMessage" to JSON ?
Or will autowrapper adapt the verification results returned by "ProblemDetial" and FluentValidation in the future?

**Comment by proudmonkey** [comment]
Hi @larssonsun,

That's an expected behavior since ExceptionMessage property is of type string. JSON object will be treated as plain text. The AutoWrapper ApiException object has 4 overload constructor methods that you can use to customize your error response.:

```csharp
ApiException(string message, int statusCode = 500, string errorCode = "", string refLink = "")
ApiException(IEnumerable<ValidationError> errors, int statusCode = 400)
ApiException(System.Exception ex, int statusCode = 500)
ApiException(object custom, int statusCode = 400)
```

For your `ProblemDetail` entity, you can use the following overload:

```csharp
ApiException(object custom, int statusCode = 400)
```
For example:

```
throw new ApiException(problemDetail);
```
For details, see: http://vmsdurano.com/asp-net-core-with-autowrapper-customizing-the-default-response-output/

For Model Validation Errors, AutoWrapper supports it by default by using the following overload:

```csharp
ApiException(IEnumerable<ValidationError> errors, int statusCode = 400)
```

For example:

```
if (ModelState.IsValid)
{
  // do something
}
else
{
        throw new ApiException(ModelState.AllErrors());
}
```
AutoWrapper is used by [ApiBoilerPlate](https://github.com/proudmonkey/ApiBoilerPlate) which uses FluentValidation.  AutoWrapper support both Data Annotation and FluentValidation.

**Comment by larssonsun** [comment]
thank you for your reply.

So autowrapper will not automatically convert these two instances, right? Yes, I can use a custom apiException to solve this problem. I'm just looking for a smarter way, haha. ProblemDetail is a machine-readable format for specifying errors in HTTP API responses based on https://tools.ietf.org/html/rfc7807 since .netcore 2.1. Also shaped like
{
"property": ["error", ..]
}
Is the default return method of FluentValidation.

Maybe autowrapper will automatically convert these two instances in the future?

Thanks again in the end.

**Comment by proudmonkey** [comment]
Yes, i'll consider adding support for ProblemDetails format in next release. :)

**Comment by larssonsun** [comment]
Very looking forward.
Now, I use the following method to solve it:
``` c#
responseBody = responseBody.Replace("\\\"", "\"").Replace("\"{", "{").Replace("}\"", "}");
```
hha..

**Comment by proudmonkey** [comment]
@larssonsun 

Just released a new version that comes with fixes in regards to these issues. You can find it here: [AutoWrapper Now Supports Problem Details For Your ASP.NET Core APIs](http://vmsdurano.com/autowrapper-now-supports-problemdetails/http://vmsdurano.com/autowrapper-now-supports-problemdetails/)

Thank you so much for all your suggestions on improving this middleware! :)
