### ISSUE TITLE
AutoWrapIgnore didn't work for Return File

### ISSUE THREAD

**Issue by arhen** [proudmonkey/AutoWrapper#27]
Hi, one of my API endpoint is serving for generate pdf. inside it's action, there couple of logic to build a PDF then return it as file view at browser with `return File(file, "application/pdf");`

Default when AutoWrapper activated, it's generate the file as json so the output seems like this broken. I've tried to add `AutoWrapIgnore` but it still didnt work.

**Comment by proudmonkey** [comment]
Can you share the relevant code here? Just remove the logic, I want to see how your API endpoint was configured. Thanks!

**Comment by arhen** [comment]
This is my entire action for generating pdf on the fly. 
I'm using DinkToPdf.
```c#
        [HttpGet("reports")]
        [AutoWrapIgnore]
        public IActionResult GetAllReport([FromQuery] string month, [FromQuery] string year)
        {
            try
            {
                if (string.IsNullOrEmpty(month) || string.IsNullOrEmpty(year))
                {
                    _logger.LogError("filter object sent from client is null.");
                    return BadRequest("Params month & year required. Object is not supported");
                }

                var allReports = _repo.Report.FindByCondition(m =>
                                    m.DateOfVerification.Value.Month.ToString().Equals(month) &&
                                    m.DateOfVerification.Value.Year.ToString().Equals(year)).ToList();

                var globalSettings = new GlobalSettings
                {
                    ColorMode = ColorMode.Color,
                    Orientation = Orientation.Landscape,
                    PaperSize = PaperKind.A4,
                    Margins = new MarginSettings { Top = 10 },
                    DocumentTitle = "PDF Report",
                };

               
                var objectSettings = new ObjectSettings
                {
                    PagesCount = true,
                    HtmlContent = TemplateGenerator.GetAllReports(allReports, idCulture.DateTimeFormat.GetMonthName(Convert.ToInt32(month)), year),
                    WebSettings = { DefaultEncoding = "utf-8", UserStyleSheet = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/css", "report_style.css") },
                    FooterSettings = { FontName = "Arial", FontSize = 9, Line = true, Right = "Page [page] of [toPage]", Left = "SF-216/2012-AVS Rev.0", Spacing = 1.8 }
                };

                var pdf = new HtmlToPdfDocument()
                {
                    GlobalSettings = globalSettings,
                    Objects = { objectSettings }
                };

                var file = _converter.Convert(pdf);

                var fileStream = new MemoryStream(file); //this is new addition based on issues #21

                _logger.LogInfo($"Report PDF Generated. Returned report PDF to client");
                //return File(file, "application/pdf");
                return new FileStreamResult(fileStream, "application/octet-stream"); // this is new addition based on issues #21
            }
            catch (Exception ex)
            {
                _logger.LogError($"Something went wrong inside GetAllReport when create pdf: {ex}");
                return StatusCode(500, "Internal server error");
            }
        }
```

**Comment by proudmonkey** [comment]
@arhen what happens if you remove/uncomment AutoWrapper refererence?

**Comment by arhen** [comment]
> @arhen what happens if you remove/uncomment AutoWrapper refererence?

It still generate json encode of my pdf since AutoWrapper has been added to my pipeline on Startup. It's become normal if I remove/uncomment `app.UseApiResponseAndExceptionWrapper();`

**Comment by proudmonkey** [comment]
Yeah that's right because AutoWrapper will still format AutoWrapIgnore endpoints to JSON.  I'll add this to the feature request. For the time being, you can place your all other enpoints that are non json outside the /api path segment so AutoWrapper will completely ignore that.

**Comment by arhen** [comment]
Hope this work asap :D. Really like ur work! good job

**Comment by arhen** [comment]
Fyi, I've tested my api with ur suggestion to wrapping out my pdf generator outside the api, but AutoWrapper still encode it.
this my configuration:

```c#
app.UseApiResponseAndExceptionWrapper( new AutoWrapperOptions { 
          ShowStatusCode = true,
          WrapWhenApiPathStartsWith = "/api" 
});
``` 
then I set my generate pdf route to `/generator/pdf`

**Comment by proudmonkey** [comment]
Could you try setting `IsApiOnly` to false instead?

```csharp
app.UseApiResponseAndExceptionWrapper( new AutoWrapperOptions { 
          ShowStatusCode = true,
          IsApiOnly = false
});
```
If that won't work then I'll create a test scenario to verify this.

**Comment by arhen** [comment]
> Could you try setting `IsApiOnly` to false instead?
> 
> ```cs
> app.UseApiResponseAndExceptionWrapper( new AutoWrapperOptions { 
>           ShowStatusCode = true,
>           IsApiOnly = false
> });
> ```
> 
> If that won't work then I'll create a test scenario to verify this.

WOW. Magical. it's work,

how is it possible? can u explain it?
I've saw the documentation about `IsApiOnly = false;`, but it is intended for SPA frameworr on the front-end right?

**Comment by proudmonkey** [comment]
Yeah it was meant to SPA or content that contains HTML or other non-JSON format. I may need to update to avoid confusion. :)

Glad it worked for you now! :)

**Comment by arhen** [comment]
yes, u need to update the docs as well. 

nice work dude! Good job. this library made my work easier on consistent Api Response Format.

**Comment by vmihalachi** [comment]
> Yeah that's right because AutoWrapper will still format AutoWrapIgnore endpoints to JSON. I'll add this to the feature request. For the time being, you can place your all other enpoints that are non json outside the /api path segment so AutoWrapper will completely ignore that.

Hi @proudmonkey, thanks for the library, it looks great! I'm having the same issue but see that the issue is closed. Is there any plans to not format to 'json' methods with 'AutoWrapIgnore' attribute?

**Comment by arhen** [comment]
> > Yeah that's right because AutoWrapper will still format AutoWrapIgnore endpoints to JSON. I'll add this to the feature request. For the time being, you can place your all other enpoints that are non json outside the /api path segment so AutoWrapper will completely ignore that.
> 
> Hi @proudmonkey, thanks for the library, it looks great! I'm having the same issue but see that the issue is closed. Is there any plan to not format to 'json' methods with 'AutoWrapIgnore' attribute?

I did but with local AutoWrapper (clone, and build manually). Change some behavior so it's not convert to json  with AutoWrapIgnore.

I hope on the next release, this issues can be truly fixed and integrated.

**Comment by Fireblade954** [comment]
having the same issue, expected [AutoWrapIgnore] would ignore everything we have a documentscontroller which i want to return a filestreamresult which doesnt work now
