### ISSUE TITLE
ApiException Example using ModelState Validation is not completed

### ISSUE THREAD

**Issue by arhen** [proudmonkey/AutoWrapper#28]
in the docs, you had given  example how to throw exception using ApiException using ModelState validation errors. But based on this [post](https://devblogs.microsoft.com/aspnet/asp-net-core-2-1-roadmap/), since NetCore version 2, "`[ApiController]` attribute will automatically responding with a 400 when validation errors occur". So on your example, this kind of response is never happen.

```json
{
    "isError": true,
    "responseException": {
        "exceptionMessage": "Request responded with validation error(s). Please correct the specified validation errors and try again.",
        "validationErrors": [
            {
                "field": "Name",
                "message": "The Name field is required."
            }
        ]
    }
}
```
It is because this validation checking will never happened,
```c#
if (ModelState.IsValid)
    {
        //Call a method to add a new record to the database
        try
        {
            var result = await SampleData.AddNew(band);
            return new ApiResponse("New record has been created to the database", result, 201);
        }
        catch (Exception ex)
        {
            //TO DO: Log ex
            throw;
        }
    }
    else
        throw new ApiException(ModelState.AllErrors());
```

The solution is, you must explain more about this state and pointing out to disable automatic model state validation. And the better approach to disable the default behavior by setting `SuppressModelStateInvalidFilter` option to true. You can set this option to true in the ConfigureServices method. Like, 
```c#
public void ConfigureServices(IServiceCollection services)
{
    services.Configure<ApiBehaviorOptions>(options =>
    {
        options.SuppressModelStateInvalidFilter = true;
    });
}
```

After adding that option, model state validation will work on Controller.

**Comment by arhen** [comment]
I dunno how it works on Net Core 3.X, but I'm still using Net Core 2.2 and it's not work in that version

**Comment by proudmonkey** [comment]
I would assume you are using FluentValidation. Setting `options.SuppressModelStateInvalidFilter = true;` will disable Automatic Model State Validation built-in to ASP.NET Core. Setting that option is subjective and yes, you have to set that if you not using the default model validation. AutoWrapper is used by [ApiBoilerPlate](https://github.com/proudmonkey/ApiBoilerPlate) which uses FluentValidation: https://github.com/proudmonkey/ApiBoilerPlate/blob/master/ApiBoilerPlate/Infrastructure/Installers/RegisterModelValidators.cs

**Comment by proudmonkey** [comment]
And as a side note, you should upgrade to .NET Core 3.x :)

**Comment by arhen** [comment]
Oh Okay, I got it. 
So, for this case, if someone who still using Net Core 2.x wanna use this case for **ONLY** this library (assume that [ApiBoilerPlate](https://github.com/proudmonkey/ApiBoilerPlate) only work since NetCore 3.x then), they should add `options.SuppressModelStateInvalidFilter = true;` and notice that they can not use another default validation state like fluent validation.

I just wanna underline this because there is on docs said that this library Support for NetCoreApp2.1 and NetCoreApp2.2 without explain about this case :)

**Comment by proudmonkey** [comment]
Good point! That's correct for v2.x. I've actually posted an article about it here: http://vmsdurano.com/asp-net-core-2-1-integrating-vmd-restapiresponsewrapper-core-to-your-rest-api-application/

I will update the docs to cover this. Thanks!

By the way, In the next release of AutoWrapper, I won't be supporting v2.x anymore to take advantage of the new features of v3.x and C# 8.

**Comment by arhen** [comment]
Well done!

**Comment by proudmonkey** [comment]
Updated the docs. Thank you so much for your feedback! I appreciate it :)
