### ISSUE TITLE
Custom Formats for API Response

### ISSUE THREAD

**Issue by fingers10** [proudmonkey/AutoWrapper#36]
Hi Vincent,

Is it possible to return the response in the format as shown in your [article](https://www.c-sharpcorner.com/article/asp-net-core-and-web-api-a-custom-wrapper-for-managing-exceptions-and-consiste/)? We have our api written in asp.net core 2.2 with the approach shown in your article. Now we are upgrading our api to asp.net core 3.1 and the code shown in the above link fails for asp.net core 3.1 api. The response gets clipped with this approach.

But now If I use AutoWrapper, then response contracts are different and since our API is already in production, we cannot change the response contract. Is it possible to achieve the same response contract here with AutoWrapper?

Old Response as per your article:
``` json
{  
    "Version": "1.0.0.0",  
    "StatusCode": 200,  
    "Message": "Request successful.",  
    "Result": [  
        "value1",  
        "value2"  
    ]  
}    
```  

New AutoWrapper Response:
```json
{
    "message": "Request successful.",
    "isError": false,
    "result": [
        {
            "date": "2019-09-16T23:37:51.5544349-05:00",
            "temperatureC": 21,
            "temperatureF": 69,
            "summary": "Mild"
        },
        {
            "date": "2019-09-17T23:37:51.554466-05:00",
            "temperatureC": 28,
            "temperatureF": 82,
            "summary": "Cool"
        },
        {
            "date": "2019-09-18T23:37:51.554467-05:00",
            "temperatureC": 21,
            "temperatureF": 69,
            "summary": "Sweltering"
        },
        {
            "date": "2019-09-19T23:37:51.5544676-05:00",
            "temperatureC": 53,
            "temperatureF": 127,
            "summary": "Chilly"
        },
        {
            "date": "2019-09-20T23:37:51.5544681-05:00",
            "temperatureC": 22,
            "temperatureF": 71,
            "summary": "Bracing"
        }
    ]
}
```

I find two issues here,

1. `StatusCode` Property is missing in AutoWrapper Response.
2. Properties names are camel casing in AutoWrapper and its pascal casing previously

Can this change be done globally? Please can you assist me further on this?

Thanks.
Abdul Rahman

**Comment by fingers10** [comment]
After some analysis I found that the code shown in your article breaks when using `AddNewtonsoftJson` in startup. Any clue on why this happens?

**Comment by proudmonkey** [comment]
Hi @fingers10 ,

AutoWrapper provides a a few options that you can configure. You can simply set `ShowStatusCode` , `ShowApiVersion` and UseCamelCaseNamingStrategy properties to achieve that. Also It should not break when using AddNewtonsoftJson() middleware. Here's an example:

ConfigureServices Method
```csharp
services.AddControllers().AddNewtonsoftJson();
```

Configure Method
```csharp
 app.UseApiResponseAndExceptionWrapper(new AutoWrapperOptions { 
                ShowStatusCode = true,
                ShowApiVersion = true,
                UseCamelCaseNamingStrategy = false
});
```

**Comment by fingers10** [comment]
Thanks for the support. Is it possible to change the ApiError class to some custom error class and is there any way to log errors in your middleware?

**Comment by proudmonkey** [comment]
Yes for both. Please read the documentation here for details: https://github.com/proudmonkey/AutoWrapper/blob/master/README.md

**Comment by fingers10** [comment]
Thanks for the support.
