### ISSUE TITLE
Exception: StatusCode cannot be set because the response has already started

### ISSUE THREAD

**Issue by sondreb** [proudmonkey/AutoWrapper#4]
Creating a new Web App with API and Angular with Visual Studio 2019 and .NET Core 3.0, then adding the app.UseApiResponseAndExceptionWrapper(); to the Configure method, will result in many exceptions like this:

"System.InvalidOperationException: StatusCode cannot be set because the response has already started."

![image](https://user-images.githubusercontent.com/309938/66144711-a216ad00-e609-11e9-8d82-296c6c767566.png)

**Comment by sondreb** [comment]
The incoming exception object to the AutoWrapperMiddleware.cs (it is line 157 that crashes)

![image](https://user-images.githubusercontent.com/309938/66145078-57496500-e60a-11e9-8346-987b1f4bc2b3.png)

Then the exception is raised here, when StatusCode is replaced from original 304 to 500:

![image](https://user-images.githubusercontent.com/309938/66145107-6af4cb80-e60a-11e9-9162-281e9bc001a2.png)

From what I can see, there is already an issue happening before this wrapper as it appears to be writing body content to an 304 (Not Modified) request.

**Comment by proudmonkey** [comment]
I tried replicating this. I created an ASP.NET Core App with Angular Template.  I then installed AutoWrapper on the project and register the middleware and it works just fine. I'm not seeing the error you get.

**Comment by sondreb** [comment]
You won't see the error on the webpage, but you'll see it in the console. If you use the project directly, you'll be able to debug as I did in the second comment.

This is with Kestrel, and not IIS Express.

Here is a recording of the problem:

![autowrapper-exception](https://user-images.githubusercontent.com/309938/66161341-5fb29780-e62c-11e9-9b24-07163181598f.gif)

Since the AutoWrapper middleware encapsulates the request, what you'll see if you run using IIS Express is a different behavior. It will render the root webpage as a JSON-structure with the HTML in the "result" field, and the Angular web page does not render at all. This is how it looks if debugging using IIS Express:

![image](https://user-images.githubusercontent.com/309938/66161192-06e2ff00-e62c-11e9-9234-f703fd60ace1.png)

Visual Studio 2019 Version 16.3.2
.NET Core Version 3.0.100

**Comment by proudmonkey** [comment]
It's clear to me now. It seems like the Wrapper isn't mean to be used within the front-end app at the moment as it will intercept all incoming requests besides "/swagger". This shouldn't happen if you have a separate API project. 

I'll see what I can do to support this scenario. Mixing front-ends with API controllers.

Thanks,
Vince

**Comment by proudmonkey** [comment]
@sondreb 

Closing this issue now. I Responded to your other issue here for the fix: https://github.com/proudmonkey/AutoWrapper/issues/5#issuecomment-538248296
