### ISSUE TITLE
HTML Content in a string property with IsApiOnly

### ISSUE THREAD

**Issue by gvisalli** [proudmonkey/AutoWrapper#41]
I have a ViewModel that contains some HTLM in a string property. I tried setting BypassHTMLValidation=true with keeping IsApiOnly=true because it is a WebAPI only.

This resulted in me losing the outer Wrapper that I wanted AutoWrapper for. I made the below adjustment to get the wrapper back.

Line 65 of WrapperBase.cs I suggest maybe something like:
&& !_options.BypassHTMLValidation && bodyAsText.IsHtml()

This fixed my problem.

What do you think?

**Comment by proudmonkey** [comment]
Hi @gvisalli,

The default settings should support string content with HTML on it. You don't have to set `BypassHTMLValidation` to true.

**Comment by gvisalli** [comment]
Using what is in nuget version v4.0.1, I have a model that has a string.

When I set this string to = "<br /><br />\\n\\n\\n<b>test<br /></b>\\ntest<br /><br />\\n\\n<b>test</b><br />\\ntest"

I get:

AutoWrapper is meant to be used for ASP.NET Core API project templates only. 
                      If you are combining API Controllers within your front-end projects like Angular, MVC, React, Blazor and other SPA frameworks that supports .NET Core,
                      then set the AutoWrapperOptions IsApiOnly property to false.

Setup with:

app.UseApiResponseAndExceptionWrapper<MapResponseObject>(new AutoWrapperOptions
            {
                UseCamelCaseNamingStrategy = false,
                BypassHTMLValidation = true, // or false
            }); ;

**Comment by proudmonkey** [comment]
Is your project contain only Web API or  a mix of MVC Controllers?

**Comment by gvisalli** [comment]
No MVC Controllers...I have a separate angular front end. Just happens that the client I am doing this for stores HTML content in some of the strings. When these strings contain that html as shown above I believe:

Regex tagRegex = new Regex(@"<\s*([^ >]+)[^>]*>.*?<\s*/\s*\1\s*>");

finds HTML content inside my string property and thinks this should be validated as HTML. This is why I had to add the !_options.BypassHTMLValidation to say skip this because I know that I do not want HTML ever validated for this WebAPI.

**Comment by proudmonkey** [comment]
Got you. I'll look into this. Thank you for providing feedback. :)

**Comment by proudmonkey** [comment]
@gvisalli ,

I did a quick test today for this scenario.

1. Created an ASP.NET Core API project. (API Only)
2. Then created the following Model class:

```csharp
public class MyObject
{
       public string FirstName { get; set; }
       public string LastName { get; set; }
}
```

3. and here's my test Controller method:

```csharp
[HttpGet("testobjectwithhtml")]
public IActionResult TestObjectWithHtml()
{
    var data = new MyObject { 
               FirstName = "<b>Vinz</b>", 
               LastName = "<br /><br />\\n\\n\\n<b>test<br /></b>\\ntest<br /><br />\\n\\n<b>test</b><br />\\ntest" };
    return Ok(data);
}
```

4. And here's the default AutoWrapper configuration on my `Startup.cs`:

```csharp
app.UseApiResponseAndExceptionWrapper();
```

5. And here's the result I got:

```
{
    "message": "GET Request successful.",
    "isError": false,
    "result": {
        "firstName": "<b>Vinz</b>",
        "lastName": "<br /><br />\\n\\n\\n<b>test<br /></b>\\ntest<br /><br />\\n\\n<b>test</b><br />\\ntest"
    }
}
```

You can see that having HTML contents in a Model property works just fine by default.

If you are getting:

"AutoWrapper is meant to be used for ASP.NET Core API project templates only.
If you are combining API Controllers within your front-end projects like Angular, MVC, React, Blazor and other SPA frameworks that supports .NET Core,
then set the AutoWrapperOptions IsApiOnly property to false."

Then try to clear the cache of your browser and rerun your API app again.

**Comment by gvisalli** [comment]
Not really sure what to say. Would love to keep using the released version, but I will just make my own from here.

I do have a lot of stuff going on with Controllers, Swagger, AutoWrapper and other things so not a simple test like yours. I figure what you did in your test works but that is a long way away from my .net core 3.1 project with all the other things.

Without this change below it fails with that error. So some how AutoMapper things I am doing both and like I said maybe I am because of swagger or something else but I just need it to work under these conditions regardless.

What is the down side to adding this? Is there a condition now that something will not happen?

if (!context.Request.Path.StartsWithSegments(new PathString(_options.WrapWhenApiPathStartsWith))
                            && !_options.BypassHTMLValidation && bodyAsText.IsHtml()
                            && context.Response.StatusCode == Status200OK)
                        {
                            if (memoryStream.Length > 0) { await awm.HandleNotApiRequestAsync(context); }
                            return;
                        }

Guess hard to trust what I say is true so up to you. I can continue to make the change when you guys make new versions.

Thanks
Greg

________________________________

**Comment by proudmonkey** [comment]
I would love to fix any issues that consumer encounters, but I need to ensure that adding this validation won't introduce any issues that's why I need something like a steps to reproduce. If your code hits within that line then that means your route is set to something else other than `/api`- which treats it as non API route by default when `IsApiOnly` is true. 

What is the route format you are hitting? Does your API route contains the `/api` segment?

**Comment by gvisalli** [comment]
My route is something like:

http://localhost/RemovedThisNameWebApi/users<http://localhost/ResuscitationWebApi/users>


Some combination of my setup where I have ControllerBase controllers returning HTML content inside the wrapped objects is a case which is not exposed much.

I will have to look at the AutoWrapper code when I have time so I can see what could be changed in order to not be forced a leading route.

My Site is http://localhost/whatever and I have routes like

http://localhost/whatever/auth/something
http://localhost/whatever/users/1

the code here:

return context.Request.Path.StartsWithSegments(new PathString(_options.WrapWhenApiPathStartsWith));

context.Request.Path:
 "/auth/something"
 "/users/1"

not

"/whatever/auth/something"
"/whatever/users/1"

So even if I set WrapWhenApiPathStartsWith = "/whatever" .. it does not hit because that part is my site and not in the api route.

Rather not be forced in setting my routes up other then how I choose.

Thanks
Greg



________________________________

**Comment by proudmonkey** [comment]
So that was the issue then. AutoWrapper expects an `/api` segment in the route for APIOnly routes to identify between API or HTML. It should work if your API endpoint route will have something like this:

 "api/auth/something"
 "api/users/1"

**Comment by proudmonkey** [comment]
[4.1.0](https://vmsdurano.com/autowrapper-4-1-0-released/) has been released with this enhancement. 

Thanks for your feedback and support. Closing this now.
