### ISSUE TITLE
ApiResponse with statusCode 4XX not setting isError: true

### ISSUE THREAD

**Issue by nick-cromwell** [proudmonkey/AutoWrapper#43]
In my opinion I've found a major inconsistency. If I return an ApiResponse from a controller in the following way:

`return new ApiResponse($"Must provide a tenantId or domain query string parameter", statusCode: StatusCodes.Status400BadRequest);`

This is the response I receive:
```json
{
    "statusCode": 400,
    "message": "Must provide a tenantId or domain query string parameter",
    "isError": false
}
```

But if an API Version is not specified in the header for that same request, this is the response I receive:
```json
{
    "statusCode": 400,
    "isError": true,
    "error": {
        "exceptionMessage": {
            "error": {
                "code": "ApiVersionUnspecified",
                "message": "An API version is required, but was not specified.",
                "innerError": null
            }
        }
    }
}
```

I would expect `isError` to be `true` regardless if an exception is throw, an ApiException is thrown with a 4XX, or an ApiResponse is returned with a 4XX. Is there are reason for not doing so?

I could throw an ApiException in the controller with a 4XX status code but that spams my logs:
![image](https://user-images.githubusercontent.com/4493128/79643735-57f2b480-8172-11ea-8312-a7a028688ec4.png)

**Comment by proudmonkey** [comment]
The `ApiResponse` object isn't meant to use for throwing non-ok requests. You should use ApiException or ApiProblemDetailsException for throwing 4XX and 5XX status codes.

>I could throw an ApiException in the controller with a 4XX status code but that spams my logs:
That's the main purpose of the logs right? to capture whatever requests. Also, you could turn-off logging by setting EnableExceptionLogging to false if you don't want to spam your logs with errors/exceptions.

**Comment by nick-cromwell** [comment]
That was my initial thought and my initial implementation - throwing an `ApiException` with status code 400. However, setting `EnableExceptionLogging` to `false` didn't prevent the exception from being logged.

I've gotten around it by using  `ApiResponse(400, new Error("Foo")) {Message = "Bad Request"}`.

I'll double check that `EnableExceptionLogging` was set to `false`, though I'm pretty certain it was. If I did want to log I wouldn't think to log a 400 at an Error level as it is and I think the exception message could be more explanatory.

**Comment by proudmonkey** [comment]
Hi @nick-cromwell - Is it safe to close this issue now?

**Comment by nick-cromwell** [comment]
I'll close it. I'm going to throw
```c#
throw new ApiException(new Error("Some bad input"), StatusCodes.Status400BadRequest));
```
for the time being so I can pull the message out consistently on the client. If I find an issue with setting `EnableExceptionLogging` to `false` I'll open a seperate issue, I haven't checked it in an environment other than my local yet.

I do think an enhancement would be having the ability to control the log message aside from the standard `Response responded with exceptions`. 

Thanks for the help.
