### ISSUE TITLE
Possible Enhancement for ignored paths

### ISSUE THREAD

**Issue by gvisalli** [proudmonkey/AutoWrapper#44]
Thanks for fixing the isApiOnly.

So under my crazy setup of a WebAPI, Swagger, AutoMapper, AutoWrapper I also at times wanted to return straight up images. So I needed a way to skip this for some paths so they did not get wrapped (like the swagger I guess). I am not sure if I will keep this. I may see about having something else serve the images because this may not be worth the extra string compare on each call. I just needed this working for now so thought it as a possible option.

This is what I did:

Added Option:

/// <summary>
/// Set the Api start paths to be ignored. The default value is null;
/// </summary>
public List<string> IgnoreWhenPathStarts { get; set; } = null;

Added the Method to check the path:

public bool IsIgnorePath(HttpContext context)
 {
            if (_options.IgnoreWhenPathStarts == null)
                return false;

            foreach (string pathStart in _options.IgnoreWhenPathStarts)
            {
                if (context.Request.Path.StartsWithSegments(new PathString(pathStart)))
                    return true;
            }

            return false;
        }
}

Check for the Ignore:

if (awm.IsIgnorePath(context) || awm.IsSwagger(context) || !awm.IsApi(context))
     await _next(context);

**Comment by proudmonkey** [comment]
Have you tried using the `[AutoWrapIgnore]` attribute for endpoints that you don't need to be wrapped?

```csharp
[HttpGet]
[AutoWrapIgnore]
public async Task<IActionResult> Get()  
{
     // Rest of the code here
}
```

**Comment by gvisalli** [comment]
That is the thing they are not endpoints. They would be some path like:

http://somewhere/avatars/guid.jpg

So no endpoints when serving these images. I do have endpoints to create some of the avatars and write them out, that is why I have them local to the api, but not sure I need it. Like I said I could serve them from some outside locations and maybe avoid this all together.


________________________________

**Comment by proudmonkey** [comment]
I would rather put all my API endpoints under `/api` so you can do whatever you want with other routes/path other than `/api`. Your making things complicated IMO.

**Comment by MongkonEiadon** [comment]
I've integrated with HealthCheck UI and I tried to Ignored following this setup

![image](https://user-images.githubusercontent.com/3174809/89724487-f3fc4080-da2d-11ea-99e1-c4338706c1e5.png)
 
but the result still remains wrapped 
![image](https://user-images.githubusercontent.com/3174809/89724502-0c6c5b00-da2e-11ea-9181-e50ad6ec8f23.png)

It's should response the data like this
![image](https://user-images.githubusercontent.com/3174809/89724515-345bbe80-da2e-11ea-9299-e36fc05581c7.png)

**Comment by proudmonkey** [comment]
@MongkonEiadon 

The order of adding middlewares matter. If you wan't to avoid your health check endpoint being wrapped, then you must register it **before** AutoWrapper:

```csharp
//Enable Healthchecks
app.UseHealthChecks("/hc", new HealthCheckOptions
{
    Predicate = _ => true,
    ResponseWriter = UIResponseWriter.WriteHealthCheckUIResponse
}).UseHealthChecksUI();

//Enable AutoWrapper.Core
app.UseApiResponseAndExceptionWrapper();
```

Alternatively, you can just simply set **IsApiOnly to false** and your existing code should work.
