### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by sajidali2444** [proudmonkey/AutoWrapper#45]
Hi, 
first of all thank you for nice package.
I am using it but one thing noted, if api method not found any record or update I am sending status code accordingly, but my client side code always receive 200 OK status.
mean api method throw exception or if I try to intentionally send 404 I always receive 200 status.
 more 
I try to find record in db using ef core suppose there is no record in db and I am sending this
return new APIResponse(StatusCodes.Status404NotFound, "Error", response);
but actual browser shows me status 200 OK in http response.

here is screenshot for your package response

![image](https://user-images.githubusercontent.com/960620/80186961-49037a80-8628-11ea-8ee0-b6dff865b53f.png)

and here actual header response
![image](https://user-images.githubusercontent.com/960620/80187039-69333980-8628-11ea-93c5-ffdaef75c053.png)

**Comment by proudmonkey** [comment]
What version of AutoWrapper you are using? I tried to replicate the issue but I'm getting the expected result.

Also, you should use `ApiException` for throwing errors, not the `ApiResponse` object.

**Comment by sajidali2444** [comment]
> What version of AutoWrapper you are using? I tried to replicate the issue but I'm getting the expected result.
> 
> Also, you should use `ApiException` for throwing errors, not the `ApiResponse` object.

I am using this version with .net core 2.2
VMD.RESTApiResponseWrapper.Core 1.0.4


here is the code i need to send back status code
public async Task<APIResponse> UpdateUser(UpdateUserViewModel model)
        {
            var response = new ResponseError();
            var userId = User.GetUserId();
            var user = await _userManager.Users.SingleOrDefaultAsync(u => (u.UserName == model.Mobile || u.Email == model.Email) && u.UserType == model.UserType);
            var userObj = await _userManager.Users.FirstOrDefaultAsync(u => u.Id == model.Id);
            if (userObj == null)
            {
                response.Errors.Add(new ResponseErrorDetail
                {
                    Description = "User not exist with specified identifier"
                });
                return new APIResponse(StatusCodes.Status404NotFound, "Errors", response);
            }

            if (user != null && userObj != null && userObj.Id != user.Id)
            {
                response.Errors.Add(new ResponseErrorDetail
                {
                    Description = "User already exist with email or phone number"
                });
                return new APIResponse(StatusCodes.Status400BadRequest, "Errors", response);
            }

            if (!string.IsNullOrEmpty(model.CountryCode))
            {
                var phoneResult = _phoneService.ValidatePhoneNumber(model.Mobile, model.CountryCode.ToUpper());
                if (phoneResult.StatusCode != HttpStatusCode.OK)
                {
                    response.Errors.Add(new ResponseErrorDetail
                    {
                        Description = phoneResult.Message.ToString()
                    });
                    return new APIResponse(StatusCodes.Status400BadRequest, "Errors", response);
                }
            }
            userObj.FirstName = model.FirstName;
            userObj.LastName = model.LastName;
            userObj.UserName = model.Mobile;
            userObj.Email = model.Email;
            userObj.Mobile = model.Mobile;
            userObj.PhoneNumber = model.Mobile;
            userObj.PhoneNumberConfirmed = true;
            userObj.IsEnabled = true;
            userObj.UserType = model.UserType;
            userObj.UpdatedOn = DateTime.Now;
            userObj.UserId = userId;
            userObj.CountryCode = model.CountryCode;
            userObj.Note = model.Note;
            userObj.IsOnline = model.IsOnline;
            userObj.AccountStatus =  model.AccountStatus;

            var result = await _userManager.UpdateAsync(userObj);
            if (result.Succeeded)
                return new APIResponse(StatusCodes.Status200OK, "Record update.", result);
            return new APIResponse(StatusCodes.Status304NotModified, "Record not updated.", result);
        }
please have a look to my code is there anything am doing wrong???

**Comment by proudmonkey** [comment]
Looks like you were using the old package. The `VMD.RESTApiResponseWrapper.Core` is deprecated and no longer maintained. Please use `AutoWrapper` instead and install version 3.0.0: https://www.nuget.org/packages/AutoWrapper.Core/3.0.0

Version 3.0.0 supports the following .NET Core frameworks:

* 2.1
* 2.2
* 3.0
* 3.1
