### ISSUE TITLE
Bug in WrapperBase/InvokeAsyncBase for StatusCode 304 or 204

### ISSUE THREAD

**Issue by sean-hurley** [proudmonkey/AutoWrapper#46]
Line 55:

![image](https://user-images.githubusercontent.com/4194398/80380849-bcde9680-8865-11ea-9d53-a0c830dddbfc.png)

Should actually be:

![image](https://user-images.githubusercontent.com/4194398/80381018-eb5c7180-8865-11ea-9c49-00ac29cf4891.png)

Otherwise that check is always false when status is 304 or 204.  Although you will ultimately still get a 304 or a 204 response, the server throws an exception:

![image](https://user-images.githubusercontent.com/4194398/80381464-966d2b00-8866-11ea-9fc8-04ebb79a67c6.png)

I'm seeing this particularly with OPTIONS requests.

**Comment by proudmonkey** [comment]
Which version of AutoWrapper you were using? I tried to replicate the issue with both GET and POST requests and I'm not able to get the error.

Using `&&` will actually always returns false as each response statuscodes will be evaluated only once - either 301 or 204.

**Comment by sean-hurley** [comment]
Using the latest version, 4.1.0

**Comment by proudmonkey** [comment]
> Try explicitly setting the context.Response.StatusCode to 204 just prior to that check (e.g., on line 54)

You can't set the status code at that time as the context is still being streamed. That's why I think you got the error.

**Comment by sean-hurley** [comment]
I should have clarified.  I just meant to make sure that status was 304 or 204 before getting to that line (wherever it happens).

When I step through the code (I cloned the master branch and referenced the project) and I get to that line, when my status is either 304 or 204, execution enters that block (and it shouldn't).  I believe that was the intent, to skip that block on 304/204 statuses.  Writing a response body on 304 may be needed, but on 204 it is not.  Here's what I get when it does:

`Connection id "0HLVAOVDV4A4E", Request id "0HLVAOVDV4A4E:00000001": An unhandled exception was thrown by the application.
System.InvalidOperationException: Response Content-Length mismatch: too few bytes written (0 of 65).
Microsoft.AspNetCore.Server.Kestrel: Error: Connection id "0HLVAOVDV4A4E", Request id "0HLVAOVDV4A4E:00000001": An unhandled exception was thrown by the application.
System.InvalidOperationException: Response Content-Length mismatch: too few bytes written (0 of 65).
`

I guess ultimately it all depends on what your intent is at that particular point.  I would think that for 204 responses, you shouldn't enter that code block that writes to the response, no?

I should also note I'm running in a Linux Docker container, which may have something to do with why I'm seeing an exception?  Not sure.  I just know the Kestrel server is throwing that exception when trying to write a response body on a 204.

**Comment by sean-hurley** [comment]
FYI: I updated my original comment.  Your initial response was correct if my status was 301 (or any other value for that matter).  301 was a typo on my part.

Based on the status code descriptions (NotModified and NoContent), I'm assuming that the code should NOT enter that block if that status code is 304 or 204.  If that is the true intent, then && would the be correct operator.

**Comment by proudmonkey** [comment]
> I'm assuming that the code should NOT enter that block if that status code is 304 or 204. If that is the true intent, then && would the be correct operator.

Are you saying that changing to `and` instead of `or` fixes the issue? I don't quite understand why because you will only get 1 response statuscode per request. Your request could return 304 `OR` 204. The `context.Response.StatusCode` will not return 304 `AND` 204 at the same time for a single request.

**Comment by proudmonkey** [comment]
Ah I'm an idiot! I think I understand your issue now. You are right - it should use `&&` operator.  I'll push a patch within the week. 

Thank you so much!

**Comment by sean-hurley** [comment]
Great, thanks!

**Comment by proudmonkey** [comment]
Closing this now :) Fix for this has been included in v4.2.0 here: https://vmsdurano.com/autowrapper-4-2-0-released/
