### ISSUE TITLE
When using with gRPC, will make the gPRC call response with 'null'

### ISSUE THREAD

**Issue by MongkonEiadon** [proudmonkey/AutoWrapper#66]
[Scenario]
I've implement the API that will have REST + gRPC

[The problem]
- This package will transfer the gRPC result and the client will not receive the correct model, then the client will got response with null

[Troubleshooting]
- I remove this package and make the API with purely gRPC instead

P.S.
Thanks for your package made my REST Easy and look great

**Comment by proudmonkey** [comment]
Hi @MongkonEiadon,

Thanks for your interests on using AutoWrapper :)

That's really interesting. I haven't tried using this with gRPC. Would you be able to throw some relevant codes here? Like what is the expected output?
