### ISSUE TITLE
Api Response for blazor app doesnt change.

### ISSUE THREAD

**Issue by Frankofoedu** [proudmonkey/AutoWrapper#67]
I have a blazor wasm app that uses an asp core API backend. I installed autowrapper.core (AutoWrapper.Core -Version 4.2.2). Tried the sample weatherforecast api. It returned the normal JSON data.

`[
    {
        "date": "2020-07-15T17:01:03.688214+01:00",
        "temperatureC": -6,
        "summary": "Balmy",
        "temperatureF": 22
    },
    {
        "date": "2020-07-16T17:01:03.6889883+01:00",
        "temperatureC": -2,
        "summary": "Cool",
        "temperatureF": 29
    },
    {
        "date": "2020-07-17T17:01:03.6889982+01:00",
        "temperatureC": 5,
        "summary": "Chilly",
        "temperatureF": 40
    },
    {
        "date": "2020-07-18T17:01:03.6889991+01:00",
        "temperatureC": 42,
        "summary": "Scorching",
        "temperatureF": 107
    },
    {
        "date": "2020-07-19T17:01:03.6889994+01:00",
        "temperatureC": -16,
        "summary": "Warm",
        "temperatureF": 4
    }
]`

instead of this

`{
    "version": "1.0.0.0",
    "statusCode": 200,
    "message": "Request successful.",
    "isError": false,
    "result": [
        {
            "date": "2019-09-16T23:37:51.5544349-05:00",
            "temperatureC": 21,
            "temperatureF": 69,
            "summary": "Mild"
        },
        {
            "date": "2019-09-17T23:37:51.554466-05:00",
            "temperatureC": 28,
            "temperatureF": 82,
            "summary": "Cool"
        },
        {
            "date": "2019-09-18T23:37:51.554467-05:00",
            "temperatureC": 21,
            "temperatureF": 69,
            "summary": "Sweltering"
        },
        {
            "date": "2019-09-19T23:37:51.5544676-05:00",
            "temperatureC": 53,
            "temperatureF": 127,
            "summary": "Chilly"
        },
        {
            "date": "2019-09-20T23:37:51.5544681-05:00",
            "temperatureC": 22,
            "temperatureF": 71,
            "summary": "Bracing"
        }
    ]`

Here is a sample repo showing the issue https://github.com/Frankofoedu/TestBlazor.git

**Comment by proudmonkey** [comment]
`AutoWrapper` needs to know if the request is an API. So in your WeatherForcastController, prefix your controller route with the `api/` segment:

```csharp
    [ApiController]
    [Route("api/[controller]")]
    public class WeatherForecastController : ControllerBase
```

and just a side note, always register the `AutoWrapper` middleware before `UseRouting` to avoid unexpected behavior. For example:

```csharp
app.UseApiResponseAndExceptionWrapper(new AutoWrapperOptions { IsApiOnly = false });
app.UseRouting();
```

Hope that Helps!

**Comment by Frankofoedu** [comment]
Thank you. The api prefix worked.
