### ISSUE TITLE
Blazor Client

### ISSUE THREAD

**Issue by dazinator** [proudmonkey/AutoWrapper#7]
It would be nice to define a generic response class that a blazor client could use, to deserialise a wrapped response.

Some sort of `WrappedApiResponse<T>` that has the consistent properties as well as the Result (of type T).

Usage would be.. the blazor client application would use HttpClient to send a request to the api, and get back a response. It could then deserialise the response body to `WrappedResponse<T>`.

**Comment by dazinator** [comment]
These need not be tied to blazor, just a POCO targeting netstandard would be enough.

**Comment by proudmonkey** [comment]
@dazinator Thanks for the suggestion.

I'm trying to understand the scenario that you described. Is your Blazor Client requesting an API that implements the AutoWraper?

**Comment by dazinator** [comment]
That's the intention yes. I'm considering adding autowrapper to my project but I'd have to change the client to deal with the new format of responses. It occurs to me this might be a common scenario.

**Comment by dazinator** [comment]
An alternative way support for .net clients could be achieved is by providing a custom http message handler. 
https://docs.microsoft.com/en-us/aspnet/web-api/overview/advanced/httpclient-message-handlers

For example, a custom message handler for an httpclient could check for the error property and throw some custom exception like an ApiException. If there was no error, it could unwrap the response, returning only the result property. This would be the mirror image of the middleware you have developed on the server side. Just some ideas!

**Comment by proudmonkey** [comment]
My apology for the late reply regarding this. I was working on v2 for the wrapper. I have released an RC version of it here to make it more customizable: [issue 6](https://github.com/proudmonkey/AutoWrapper/issues/6#issuecomment-541520067)

I will work on this next. Thank you for your feedback. :)

**Comment by proudmonkey** [comment]
@dazinator My apology for getting back late. Been so busy the past weeks. Anyway, I've created a Delegating Handler for this as you have suggested. The initial package in in RC: [AutoWrapper.Server](https://www.nuget.org/packages/AutoWrapper.Server/1.0.0-rc)

Sample Usage:

```csharp
public async Task<IEnumerable<WeatherForecast>> WeatherForecasts()
{
    HttpClient client = HttpClientFactory.Create(new AutoWrapper.Server.UnWrapResponseHandler());

    client.BaseAddress = new Uri("https://localhost:5001");
    client.DefaultRequestHeaders.Accept.Clear();
    client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

    var httpResponse = await client.GetAsync("/api/v1/persons1");

    IEnumerable<WeatherForecast> forecasts = null;
    if (httpResponse.IsSuccessStatusCode)
    {
        var contentResult = await httpResponse.Content.ReadAsStringAsync();
        forecasts = JsonSerializer.Deserialize<IEnumerable<WeatherForecast>>(contentResult, AutoWrapper.Server.Helpers.JsonSettings.JsonDeserializerSettings());
    }


    return forecasts;
}
```

You can also use `HttpClientFactory` to inject the Handler, for example:

```csharp
services.AddTransient<AutoWrapper.Server.UnWrapResponseHandler()>();


services.AddHttpClient<IApiConnect, ApiConnect>(client =>
{
     client.BaseAddress = new Uri(config["ApiResourceBaseUrls:SampleApi"]);
     client.DefaultRequestHeaders.Accept.Clear();
     client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue(HttpContentMediaTypes.JSON));
})
.AddHttpMessageHandler<AutoWrapper.Server.UnWrapResponseHandler()>()
```
