### ISSUE TITLE
Package AutoWrapper.Core 1.1.0 is not compatible with netcoreapp2.2 (.NETCoreApp,Version=v2.2). Package AutoWrapper.Core 1.1.0 supports: netcoreapp3.0 (.NETCoreApp,Version=v3.0)

### ISSUE THREAD

**Issue by lastlink** [proudmonkey/AutoWrapper#8]
`error: Package AutoWrapper.Core 1.1.0 is not compatible with netcoreapp2.2 (.NETCoreApp,Version=v2.2). Package AutoWrapper.Core 1.1.0 supports:
netcoreapp3.0 (.NETCoreApp,Version=v3.0)
error: Package 'AutoWrapper.Core' is incompatible with 'all' frameworks in project 'xxx.csproj.`

Should target dotnet core 2 unless it's completely incompatible.

**Comment by proudmonkey** [comment]
Thank you for your feedback. Will work on this.

**Comment by proudmonkey** [comment]
@lastlink I've relested v2 RC2 to add support for `netcoreapp2.1` and `netcoreapp2.2` here: https://www.nuget.org/packages/AutoWrapper.Core/2.0.0-rc2

You need to add `Newtonsoft.json` before adding `AutoWrapper`. I've tested it using `netcoreapp2.1` but I haven't tested it using `netcoreapp2.2`. Try it out and let me know you feedback.

Thanks,
Vince

**Comment by proudmonkey** [comment]
@lastlink - Closing this now. Here's an article I posted that highlights the new features of AutoWrapper: [ASP.NET Core with AutoWrapper: Customizing the Default Response Output](http://vmsdurano.com/asp-net-core-with-autowrapper-customizing-the-default-response-output/)
