### ISSUE TITLE
Need the wrapper to ignore $metadata endpoint when used in an API project containing OData endpoints.

### ISSUE THREAD

**Issue by ronaldwalcott** [proudmonkey/AutoWrapper#80]
Good day

I have been using the wrapper as below

`            app.UseApiResponseAndExceptionWrapper(new AutoWrapperOptions
            {
                IgnoreWrapForOkRequests = true,
            });`

but after implementing OData for some of my APIs I get the below message when calling the $metadata endpoint

This page contains the following errors:
error on line 1 at column 1: Document is empty 
 
![Screenshot 2020-10-14 201200](https://user-images.githubusercontent.com/34167625/96058888-7522ea00-0e5a-11eb-80eb-f5e2596bb1e0.png)

commenting out the code allows the XML metadata to display
 
![Screenshot 2020-10-14 201409](https://user-images.githubusercontent.com/34167625/96058858-63d9dd80-0e5a-11eb-9b28-e193f4260c8c.png)

Is there a way to ignore this endpoint and still use the wrapper on other endpoints?

Thanks

**Comment by proudmonkey** [comment]
Hi,

If you can group all your API endpoints that uses AutoWrapper, then you can try setting the `WrapWhenApiPathStartsWith` and it should ignore the rest of the endpoint.

https://github.com/proudmonkey/AutoWrapper#wrapwhenapipathstartswith
