### ISSUE TITLE
How tu use AutoWrapperOptions in .NET enviroment

### ISSUE THREAD

**Issue by celmarek** [proudmonkey/AutoWrapper#82]
Hello, is any example how tu use 👍

app.UseApiResponseAndExceptionWrapper(new AutoWrapperOptions { UseApiProblemDetailsException = true }); 

in .net enviroment ? 

p.s: How to use [AutoWrapperPropertyMap(Prop.)] in .NET  ?

**Comment by proudmonkey** [comment]
I'm not sure what you mean by .NET emvironment, but you can find the documentation about their usage in the README file: https://github.com/proudmonkey/AutoWrapper/blob/master/README.md

You can also find a few links there that shows how to use them:

http://vmsdurano.com/autowrapper-now-supports-problemdetails/
https://vmsdurano.com/asp-net-core-with-autowrapper-customizing-the-default-response-output/

**Comment by celmarek** [comment]
Thx for fast replay, 

I Want to use this future in ASP.NET Web (Net Framework) api not in ASP.NET Core.

**Comment by proudmonkey** [comment]
Hi,

`AutoWrapper` does not support the full .NET Framework. However, I've written a package for it for traditional ASP.NET version here: https://github.com/proudmonkey/RESTApiResponseWrapper.Net

Though, keep in mind that I no longer maintain that library.
