### ISSUE TITLE
signalr error

### ISSUE THREAD

**Issue by mansai** [proudmonkey/AutoWrapper#95]
Failed to start the connection: Error: None of the transports

 public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
                app.UseSwagger();
                app.UseSwaggerUI(c => c.SwaggerEndpoint("/swagger/v1/swagger.json", "Solution1.WebAPI v1"));
            }

            app.UseHttpsRedirection();
            app.UseApiResponseAndExceptionWrapper();//Delete this line is ok
            app.UseRouting();

            app.UseCors("LimitRequests");

            app.UseAuthorization();

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllers();
                endpoints.MapHub<ChatHub>("/api2/chathub");
            });
        }
![image](https://user-images.githubusercontent.com/3213405/103532887-08524580-4ec7-11eb-8914-edf0d07fa62d.png)

![image](https://user-images.githubusercontent.com/3213405/103532764-c7f2c780-4ec6-11eb-89ec-dd762875c671.png)
![image](https://user-images.githubusercontent.com/3213405/103532848-ece73a80-4ec6-11eb-9df6-e9b4ab679eed.png)

**Comment by mansai** [comment]
[Solution1.WebAPI.zip](https://github.com/proudmonkey/AutoWrapper/files/5764516/Solution1.WebAPI.zip)

**Comment by proudmonkey** [comment]
Interesting. I haven't tried using AutoWrapper in combination of APIs and SignalR. Have you tried setting `IsApiOnly` to `false` and set the `WrapWhenApiPathStartsWith` options?

**Comment by mansai** [comment]
app.UseApiResponseAndExceptionWrapper<MapResponseObject>(new AutoWrapperOptions { ShowStatusCode = true, IsApiOnly = false, BypassHTMLValidation = true, WrapWhenApiPathStartsWith = "/api2/chatHub/negotiate" });

is error
I custom a OptionBase:IgnorePath
 app.UseApiResponseAndExceptionWrapper<MapResponseObject>(new AutoWrapperOptions { ShowStatusCode = true, IsApiOnly=false, BypassHTMLValidation=true, IgnorePath = "/api2/chatHub/negotiate" });

Add code: WrapperBase.cs  at line 63
`var path = context.Request.Path.Value;
                        if (_options.IgnorePath!=null && _options.IgnorePath== path)
                        {
                            await awm.WrapIgnoreAsync(context, bodyAsText);
                        }`

**Comment by proudmonkey** [comment]
If you've added a custom option to ignore a specific path, you can just return instead of calling `WrapIgnoreAsync`

**Comment by mansai** [comment]
Is that so?

`if (_options.IgnorePath!=null && _options.IgnorePath== path)
                        {
                            return; 
                        }`

**Comment by proudmonkey** [comment]
With the ExcludePath comes with the latest version, I think this should resolved your issue. See; https://vmsdurano.com/autowrapper-4-5-0-released/
